apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: eu.gcr.io/nice-script-280016/redishop
        ports:
        - containerPort: 8000
        env:
          - name: BROKER_URL
            value: "broker-redis-master"
          - name: REDIS_URL
            value: "users-redis-master"
          - name: POSTGRES_URL
            value: "users-postgresql"
          - name: SERVICE
            value: "user"
          - name: BACKEND
            value: "postgres"
            # value: "redis"
          - name: "URL_USER"
            value: "http://users"
          - name: "URL_ORDER"
            value: "http://orders"
          - name: "URL_STOCK"
            value: "http://stock"
          - name: "URL_PAYMENT"
            value: "http://payments"
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
      - name: stock
        image: eu.gcr.io/nice-script-280016/redishop
        ports:
        - containerPort: 8000
        env:
          - name: BROKER_URL
            value: "broker-redis-master"
          - name: REDIS_URL
            value: "stock-redis-master"
          - name: POSTGRES_URL
            value: "stock-postgresql"
          - name: SERVICE
            value: "stock"
          - name: BACKEND
            value: "postgres"
            # value: "redis"
          - name: "URL_USER"
            value: "http://users"
          - name: "URL_ORDER"
            value: "http://orders"
          - name: "URL_STOCK"
            value: "http://stock"
          - name: "URL_PAYMENT"
            value: "http://payments"
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: eu.gcr.io/nice-script-280016/redishop
        ports:
        - containerPort: 8000
        env:
          - name: BROKER_URL
            value: "broker-redis-master"
          - name: REDIS_URL
            value: "orders-redis-master"
          - name: POSTGRES_URL
            value: "users-postgresql"
          - name: SERVICE
            value: "order"
          - name: BACKEND
            value: "postgres"
            # value: "redis"
          - name: "URL_USER"
            value: "http://users"
          - name: "URL_ORDER"
            value: "http://orders"
          - name: "URL_STOCK"
            value: "http://stock"
          - name: "URL_PAYMENT"
            value: "http://payments"
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: eu.gcr.io/nice-script-280016/redishop
        ports:
        - containerPort: 8000
        env:
          - name: BROKER_URL
            value: "broker-redis-master"
          - name: REDIS_URL
            value: "payments-redis-master"
          - name: POSTGRES_URL
            value: "payments-postgresql"
          - name: SERVICE
            value: "payment"
          - name: BACKEND
            value: "postgres"
            # value: "redis"
          - name: "URL_USER"
            value: "http://users"
          - name: "URL_ORDER"
            value: "http://orders"
          - name: "URL_STOCK"
            value: "http://stock"
          - name: "URL_PAYMENT"
            value: "http://payments"
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
